### NUMPY CODING

***trapti patel (software engineer)***

In [137]:
import numpy as np

In [138]:
myar=np.array([1,2,3,4,5],np.int64)

In [139]:
myar

array([1, 2, 3, 4, 5])

In [140]:
type(myar)

numpy.ndarray

In [141]:
myar.dtype

dtype('int64')

In [142]:
myar=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int64)

In [143]:
myar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
myar[0,2]

np.int64(3)

In [145]:
myar[0,2]=44

In [146]:
myar

array([[ 1,  2, 44],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [147]:
myar.shape

(3, 3)

In [148]:
myar.argmax()

np.int64(2)

### conversion from other python data structure(eq-list tuples)

In [149]:
lst=[3,4,5,6,7,0]

In [150]:
npar=np.array(lst)

In [151]:
npar

array([3, 4, 5, 6, 7, 0])

### intrinsic numpy array creation object (eq-arange,ones zeros)

In [152]:
zeros=np.zeros((2,5))

In [153]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [154]:
zeros.dtype

dtype('float64')

In [155]:
zeros.shape

(2, 5)

In [156]:
ones=np.ones((3,4))

In [157]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [158]:
arng=np.arange(10)

In [159]:
arng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
lspace=np.linspace(1,5,12)

In [161]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [162]:
emp=np.empty((4,6))

In [163]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 1.69121639e-306, 1.05701279e-307,
        1.24610383e-306, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.37962320e-306,
        6.89812281e-307, 1.24611674e-306, 6.23060065e-307],
       [6.89813978e-307, 8.90104239e-307, 6.23055651e-307,
        1.60219306e-306, 1.69119737e-306, 2.56765117e-312]])

In [164]:
emp[0,1]

np.float64(1.8691869854601642e-306)

In [165]:
emp_like=np.empty_like(emp)

In [166]:
emp_like

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 1.69121639e-306, 1.05701279e-307,
        1.24610383e-306, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.37962320e-306,
        6.89812281e-307, 1.24611674e-306, 6.23060065e-307],
       [6.89813978e-307, 8.90104239e-307, 6.23055651e-307,
        1.60219306e-306, 1.69119737e-306, 2.56765117e-312]])

In [167]:
ide=np.identity(10)

In [168]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [169]:
reshap_ar=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [170]:
reshap_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [171]:
reshap_ar.shape

(12,)

In [172]:
reshap=reshap_ar.reshape(4,3)

In [173]:
reshap

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [174]:
oned_ar=reshap.ravel()

In [175]:
oned_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### numpy axis

In [176]:
arr1=np.array([[1,2],[3,4],[5,6]])

In [177]:
arr2=np.array([[0,1],[0,3],[1,2]])

In [178]:
arr1+arr2

array([[1, 3],
       [3, 7],
       [6, 8]])

In [179]:
[1,2]+[2,3]

[1, 2, 2, 3]

In [180]:
arr1*arr2

array([[ 0,  2],
       [ 0, 12],
       [ 5, 12]])

In [181]:
op=np.array([4,3,0,8,2,5,1,6])

In [182]:
op

array([4, 3, 0, 8, 2, 5, 1, 6])

In [183]:
op.argmax

<function ndarray.argmax>

In [184]:
op.argmax()

np.int64(3)

In [185]:
op.argmin()

np.int64(2)

In [186]:
op.argsort()

array([2, 6, 4, 1, 0, 5, 7, 3])

In [187]:
op.sum()

np.int64(29)

In [188]:
op.size

8

In [189]:
arr1-arr2

array([[1, 1],
       [3, 1],
       [4, 4]])

In [193]:
a3=reshap_ar

In [194]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [197]:
a3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [200]:
arr1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [201]:
arr1.flat

In [203]:
for  item in arr1.flat:
    print(item)

1
2
3
4
5
6


In [204]:
arr1.sum(axis=1)

array([ 3,  7, 11])

In [205]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [206]:
arr1.sum(axis=0)

array([ 9, 12])

In [207]:
arr1.ndim

2

In [209]:
arr1.nbytes

48

In [210]:
arr1.argsort()

array([[0, 1],
       [0, 1],
       [0, 1]])